#pragma once


//Các thông số của MARIO
//Các transformation
#define	MARIO_SMALL_FORM	0
#define	MARIO_BIG_FORM		1
#define MARIO_FIRE_FORM		2
#define MARIO_RACCOON_FORM	3

// Chiều cao và rộng ở các form
#define MARIO_BIG_BBOX_WIDTH  16
#define MARIO_BIG_BBOX_HEIGHT 27
#define MARIO_SMALL_BBOX_WIDTH  16
#define MARIO_SMALL_BBOX_HEIGHT 16
#define MARIO_FIRE_BBOX_WIDTH 16
#define MARIO_FIRE_BBOX_HEIGHT 27
#define MARIO_RACCOON_BBOX_WIDTH 24
#define MARIO_RACCOON_BBOX_HEIGHT 27
#define MARIO_BBOX_SQUAT_HEIGHT	18
#define MARIO_BBOX_SQUAT_WIDTH	14


//Các chỉ số thời gian và tốc độ
#define MARIO_UNTOUCHABLE_TIME			1000
#define MARIO_WALKING_SPEED				0.1f
#define MARIO_JUMP_SPEED_Y				0.3f
#define MARIO_SUPER_JUMP_SPEED			0.5f
#define MARIO_JUMP_DEFLECT_SPEED		0.3f
#define MARIO_WALK_DEFELCT_SPEED		0.07f
#define MARIO_BRAKE_DEFLECT_SPEED		0.05f
#define MARIO_GRAVITY					0.002f
#define MARIO_LOWER_GRAVITY				0.001f
#define MARIO_DIE_DEFLECT_SPEED			0.5f
#define BUFF_SPEED						0.008f	// tốc độ tăng lên khi tích stack
#define POWER_METER_FULL				7		// số stack tối đa		//thời gian để tích 1 stack
#define POWER_MELTER_MINIMUM			0
#define POWER_MELTER_BUFF_SPEED_LEVEL	4
#define STACK_TIME					    500			//thời gian để tích 1 stack
#define LOSE_STACK_TIME					300
#define MARIO_FRICTION					0.08f
#define MARIO_SUPER_JUMP_TIME			300
#define MARIO_FLYING_LIMITED_TIME		 2000
#define MARIO_FLOATING_SPEED_Y			-0.02f
#define MARIO_FALLING_SPEED				0.02f
//Các trạng thái của Mario
#define MARIO_STATE_IDLE				0
#define MARIO_STATE_WALKING				100
#define MARIO_STATE_RUNNING				200
#define MARIO_STATE_JUMPING				300
#define MARIO_STATE_SUPER_JUMPING		400
#define MARIO_STATE_BRAKING				500
#define MARIO_STATE_KICK				600
#define MARIO_STATE_PICK				700
#define MARIO_STATE_DEATH				800
#define MARIO_STATE_STOP				900
#define MARIO_STATE_SQUAT				1000
#define MARIO_STATE_SHOOT_FIREBALL		1100
#define MARIO_STATE_TAILATTACK			1200
#define MARIO_STATE_FLOATING			1300
#define MARIO_STATE_FLYING				1400


//Mario's Animations
#define MARIO_ANI_SMALL_IDLE			0
#define MARIO_ANI_BIG_IDLE				1
#define MARIO_ANI_FIRE_IDLE				2
#define MARIO_ANI_RACCOON_IDLE			3

#define MARIO_ANI_SMALL_WALKING			4
#define MARIO_ANI_BIG_WALKING			5
#define MARIO_ANI_FIRE_WALKING			6
#define MARIO_ANI_RACCOON_WALKING		7

#define MARIO_ANI_SMALL_JUMPING			8
#define MARIO_ANI_BIG_JUMPING			9
#define MARIO_ANI_FIRE_JUMPING			10
#define MARIO_ANI_RACCOON_JUMPING		11

#define MARIO_ANI_SMALL_RUNNING			12
#define MARIO_ANI_BIG_RUNNING			13
#define MARIO_ANI_FIRE_RUNNING			14
#define MARIO_ANI_RACCOON_RUNNING		15

#define MARIO_ANI_SMALL_FULL_RUNNING	16
#define MARIO_ANI_BIG_FULL_RUNNING		17
#define MARIO_ANI_FIRE_FULL_RUNNING		18
#define MARIO_ANI_RACCOON_FULL_RUNNING	19


#define MARIO_ANI_SMALL_LONG_JUMPING	20
#define MARIO_ANI_BIG_LONG_JUMPING		21
#define MARIO_ANI_FIRE_LONG_JUMPING		22
#define MARIO_ANI_RACCOON_LONG_JUMPING	23

#define MARIO_ANI_SMALL_FULL_BRAKING	24
#define MARIO_ANI_BIG_FULL_BRAKING		25
#define MARIO_ANI_FIRE_FULL_BRAKING		26
#define MARIO_ANI_RACCOON_FULL_BRAKING	27

#define MARIO_ANI_SMALL_KICK_SHELL		28
#define MARIO_ANI_BIG_KICK_SHELL		29
#define MARIO_ANI_FIRE_KICK_SHELL		30
#define MARIO_ANI_RACCOON_KICK_SHELL	31

#define MARIO_ANI_SMALL_HOLD_SHELL_IDLE	32
#define MARIO_ANI_BIG_HOLD_SHELL_IDLE	33
#define MARIO_ANI_FIRE_HOLD_SHELL_IDLE	34
#define MARIO_ANI_RACCOON_HOLD_SHELL_IDLE	35

#define MARIO_ANI_SMALL_HOLD_SHELL_RUNNING		36
#define MARIO_ANI_BIG_HOLD_SHELL_RUNNING		37
#define MARIO_ANI_FIRE_HOLD_SHELL_RUNNING		38
#define MARIO_ANI_RACCOON_HOLD_SHELL_RUNNING	39

#define MARIO_ANI_BIG_SQUAT						40
#define MARIO_ANI_FIRE_SQUAT					41
#define MARIO_ANI_RACCOON_SQUAT					42

#define MARIO_ANI_SHOOT_FIRE_BALL				43
#define MARIO_ANI_TAILATTACK					44
#define MARIO_ANI_FLOATING						45
#define MARIO_ANI_FLYING						46
#define MARIO_ANI_DIE							47

#define MARIO_DO_NOTHING		0
#define MARIO_SKILL_FIREBALL	1
#define MARIO_SKILL_TAILATTCK	2



//GOOMBA
#define GOOMBA_WALKING_SPEED 0.05f;
#define GOOMBA_GRAVITY		0.002f;
#define GOOMBA_DIE_DEFLECT_SPEED 0.4f

#define GOOMBA_BBOX_WIDTH 16
#define GOOMBA_BBOX_HEIGHT 15
#define GOOMBA_BBOX_HEIGHT_DIE 9

#define GOOMBA_STATE_WALKING		100
#define GOOMBA_STATE_DIE			200
#define GOOMBA_STATE_BEING_STROMPED	300
#define GOOMBA_STATE_BEING_SKILLED	400
#define GOOMBA_STATE_INACTIVE		500

#define GOOMBA_ANI_WALKING			0
#define GOOMBA_ANI_DIE				1


#define GOOMA_INACTIVE_TIME		500

//KoopaTroopa
#define KOOPATROOPA_TYPE_RED	0
#define KOOPATROOPA_TYPE_GREEN	1

#define KOOPATROOPA_WALKING_SPEED 0.03f
#define KOOPATROOPA_GRAVITY 0.002f
#define KOOPATROOPA_BUMP_SPEED	0.2f
#define KOOPATROOPA_DIE_DEFLECT_SPEED 0.5f
#define KOOPATROPPA_EXIT_HIDING_DEFLECT_SPEED	0.01f
#define KOOPATROOPA_EXIT_SHELL_TIME	5000
#define KOOPATROOPA_INACTIVE_TIME	1200
#define KOOPATROOPA_TURN_WALKING_TIME	500

#define KOOPATROOPA_BBOX_WIDTH 16
#define KOOPATROOPA_BBOX_HEIGHT 26
#define KOOPATROOPA_BBOX_HEIGHT_HIDING 16


#define KOOPATROOPA_STATE_WALKING 100
#define KOOPATROOPA_STATE_HIDING 200
#define KOOPATROOPA_STATE_IS_PICKED_UP 300
#define KOOPATROOPA_STATE_BEING_SKILLED	400
#define KOOPATROOPA_STATE_IS_BUMPED 500
#define KOOPATROOPA_STATE_INACTIVE	600
#define KOOPATROOPA_STATE_EXIT_SHELL	700


#define KOOPATROOPA_GREEN_ANI_WALKING	0
#define KOOPATROOPA_GREEN_ANI_HIDING	1
#define KOOPATROOPA_GREEN_ANI_BUMPING	2
#define KOOPATROOPA_GREEN_ANI_DEATH		3
#define KOOPATROOPA_RED_ANI_WALKING		4
#define KOOPATROOPA_RED_ANI_HIDING		5
#define KOOPATROOPA_RED_ANI_BUMPING		6
#define KOOPATROOPA_RED_ANI_DEATH		7
#define KOOPATROOPA_GREEN_ANI_EXIT_SHELL	8
#define KOOPATROOPA_RED_ANI_EXIT_SHELL	9
//PiranhaPlant
#define PIRANHAPLANT_BBOX_WIDTH			16
#define PIRANHANPLANT_BBOX_HEIGHT		32

#define PIRIHANPLANT_STATE_DARTING		0
#define PIRIHANPLANT_STATE_BITING		1
#define PIRRIHANPLANT_STATE_DIE			2

#define PIRIHANPLANT_ANI_DARTING		0
#define PIRIHANPLANT_ANI_BITTING		1

#define PRIHANPLANT_SWITCHING_STATE_TIME	2000
//FIREBALL
#define FIREBALL_GRAVITY 0.008f
#define FIREBALL_SPEED_NX	0.15f
#define FIREBALL_SPEED_NY 0.09f
#define FIREBALL_BBOX_HEIGHT 16
#define FIREBALL_BBOX_WIDTH 8
#define FIREBALL_STATE_NORMAL	100
#define FIREBALL_STATE_EXPLODE		200
#define FIREBALL_STATE_INACTIVE	300
#define FIREBALL_ANI_NORMAL		0
#define FIREBALL_ANI_EXPLODE	1
#define FIREBALL_INACTIVE_TIME	200
//BLOCK
#define GROUND_BBOX_WIDTH  16
#define GROUND_BBOX_HEIGHT 16
//Block
#define BLOCK_BBOX_WIDTH  16
#define BLOCK_BBOX_HEIGHT 16
#define ID_TEX_BBOX -100		// special texture to draw object bounding box
//Brick
#define BRICK_BBOX_WIDTH  16
#define BRICK_BBOX_HEIGHT 16
#define INVISIBLEBRICK_TYPE_GROUND	0
#define INVISIBLEBRICK_TYPE_BLOCK	1
//Game PLAY 
#define SCENE_SECTION_UNKNOWN -1
#define SCENE_SECTION_TEXTURES 2
#define SCENE_SECTION_SPRITES 3
#define SCENE_SECTION_ANIMATIONS 4
#define SCENE_SECTION_ANIMATION_SETS	5
#define SCENE_SECTION_OBJECTS	6
#define SCENE_SECTION_MAPS	7
#define OBJECT_TYPE_MARIO	0
#define OBJECT_TYPE_BRICK	1
#define OBJECT_TYPE_GOOMBA	2
#define OBJECT_TYPE_KOOPAS	3
#define OBJECT_TYPE_BLOCKS	5
#define OBJECT_TYPE_GROUNDS	4
#define OBJECT_TYPE_PIPES	6
#define OBJECT_TYPE_INVISIBLEBRICK	7
#define OBJECT_TYPE_PORTAL	50
#define MAX_SCENE_LINE 1024
//Tile Map
#define TILE_WIDTH 16
#define TILE_HEIGHT 16

//Pipe
#define PIPE_BBOX_WIDTH  32
#define PIPE_BBOX_HEIGHT 16
//SETTING
#define WINDOW_CLASS_NAME L"SuperMarioBros3"
#define MAIN_WINDOW_TITLE L"Super Mario Bros 3"
#define BACKGROUND_COLOR D3DCOLOR_XRGB(181, 236, 243)
#define SCREEN_WIDTH 320
#define SCREEN_HEIGHT 240
#define MAX_FRAME_RATE 120
