#pragma once


//Các thông số của MARIO
//Các transformation
#define	MARIO_SMALL_FORM	0
#define	MARIO_BIG_FORM		1
#define MARIO_FIRE_FORM		2
#define MARIO_RACCOON_FORM	3

// Chiều cao và rộng ở các form
#define MARIO_BIG_BBOX_WIDTH  16
#define MARIO_BIG_BBOX_HEIGHT 27
#define MARIO_SMALL_BBOX_WIDTH  16
#define MARIO_SMALL_BBOX_HEIGHT 16
#define MARIO_FIRE_BBOX_WIDTH 16
#define MARIO_FIRE_BBOX_HEIGHT 27
#define MARIO_RACCOON_BBOX_WIDTH 24
#define MARIO_RACCOON_BBOX_HEIGHT 27
#define MARIO_BBOX_SQUAT_HEIGHT	18
#define MARIO_BBOX_SQUAT_WIDTH	14
#define MARIO_RACCOON_TAILATTACK_WIDTH	28


//Các chỉ số thời gian và tốc độ
#define MARIO_UNTOUCHABLE_TIME			1000
#define MARIO_WALKING_SPEED				0.08f
#define MARIO_JUMP_SPEED_Y				0.3f
#define MARIO_SUPER_JUMP_SPEED			0.5f
#define MARIO_JUMP_DEFLECT_SPEED		0.3f
#define MARIO_WALK_DEFELCT_SPEED		0.07f
#define MARIO_BRAKE_DEFLECT_SPEED		0.08f
#define MARIO_GRAVITY					0.002f
#define MARIO_LOWER_GRAVITY				0.001f
#define MARIO_DIE_DEFLECT_SPEED			0.5f
#define BUFF_SPEED						0.008f	// tốc độ tăng lên khi tích stack
#define POWER_METER_FULL				7		// số stack tối đa		//thời gian để tích 1 stack
#define POWER_MELTER_MINIMUM			0
#define POWER_MELTER_BUFF_SPEED_LEVEL	4
#define STACK_TIME						200			//thời gian để tích 1 stack
#define LOSE_STACK_TIME					100
#define MARIO_FRICTION					0.08f
#define MARIO_SUPER_JUMP_TIME			300
#define MARIO_FLYING_LIMITED_TIME		2000
#define MARIO_FLOATING_SPEED_Y			0.01f
#define MARIO_FALLING_SPEED				0.03f
//Các trạng thái của Mario
#define MARIO_STATE_IDLE				0
#define MARIO_STATE_WALKING				100
#define MARIO_STATE_RUNNING				200
#define MARIO_STATE_JUMPING				300
#define MARIO_STATE_SUPER_JUMPING		400
#define MARIO_STATE_BRAKING				500
#define MARIO_STATE_KICK				600
#define MARIO_STATE_PICK				700
#define MARIO_STATE_DEATH				800
#define MARIO_STATE_STOP				900
#define MARIO_STATE_SQUAT				1000
#define MARIO_STATE_SHOOT_FIREBALL		1100
#define MARIO_STATE_TAILATTACK			1200
#define MARIO_STATE_FLOATING			1300
#define MARIO_STATE_FLYING				1400


//Mario's Animations
#define MARIO_ANI_SMALL_IDLE			0
#define MARIO_ANI_BIG_IDLE				1
#define MARIO_ANI_FIRE_IDLE				2
#define MARIO_ANI_RACCOON_IDLE			3

#define MARIO_ANI_SMALL_WALKING			4
#define MARIO_ANI_BIG_WALKING			5
#define MARIO_ANI_FIRE_WALKING			6
#define MARIO_ANI_RACCOON_WALKING		7

#define MARIO_ANI_SMALL_JUMPING			8
#define MARIO_ANI_BIG_JUMPING			9
#define MARIO_ANI_FIRE_JUMPING			10
#define MARIO_ANI_RACCOON_JUMPING		11

#define MARIO_ANI_SMALL_RUNNING			12
#define MARIO_ANI_BIG_RUNNING			13
#define MARIO_ANI_FIRE_RUNNING			14
#define MARIO_ANI_RACCOON_RUNNING		15

#define MARIO_ANI_SMALL_FULL_RUNNING	16
#define MARIO_ANI_BIG_FULL_RUNNING		17
#define MARIO_ANI_FIRE_FULL_RUNNING		18
#define MARIO_ANI_RACCOON_FULL_RUNNING	19


#define MARIO_ANI_SMALL_LONG_JUMPING	20
#define MARIO_ANI_BIG_LONG_JUMPING		21
#define MARIO_ANI_FIRE_LONG_JUMPING		22
#define MARIO_ANI_RACCOON_LONG_JUMPING	23

#define MARIO_ANI_SMALL_FULL_BRAKING	24
#define MARIO_ANI_BIG_FULL_BRAKING		25
#define MARIO_ANI_FIRE_FULL_BRAKING		26
#define MARIO_ANI_RACCOON_FULL_BRAKING	27

#define MARIO_ANI_SMALL_KICK_SHELL		28
#define MARIO_ANI_BIG_KICK_SHELL		29
#define MARIO_ANI_FIRE_KICK_SHELL		30
#define MARIO_ANI_RACCOON_KICK_SHELL	31

#define MARIO_ANI_SMALL_HOLD_SHELL_IDLE	32
#define MARIO_ANI_BIG_HOLD_SHELL_IDLE	33
#define MARIO_ANI_FIRE_HOLD_SHELL_IDLE	34
#define MARIO_ANI_RACCOON_HOLD_SHELL_IDLE	35

#define MARIO_ANI_SMALL_HOLD_SHELL_RUNNING		36
#define MARIO_ANI_BIG_HOLD_SHELL_RUNNING		37
#define MARIO_ANI_FIRE_HOLD_SHELL_RUNNING		38
#define MARIO_ANI_RACCOON_HOLD_SHELL_RUNNING	39

#define MARIO_ANI_BIG_SQUAT						40
#define MARIO_ANI_FIRE_SQUAT					41
#define MARIO_ANI_RACCOON_SQUAT					42

#define MARIO_ANI_SHOOT_FIRE_BALL				43
#define MARIO_ANI_TAILATTACK					44
#define MARIO_ANI_FLOATING						45
#define MARIO_ANI_FLYING						46
#define MARIO_ANI_DIE							47

#define MARIO_DO_NOTHING		0
#define MARIO_SKILL_FIREBALL	1
#define MARIO_SKILL_TAILATTCK	2



//GOOMBA
#define GOOMBA_WALKING_SPEED 0.03f;
#define GOOMBA_GRAVITY		0.002f;
#define GOOMBA_DIE_DEFLECT_SPEED_Y 0.4f
#define GOOMBA_DIE_DEFLECT_SPEED_X 0.1f

#define GOOMBA_BBOX_WIDTH 16
#define GOOMBA_BBOX_HEIGHT 15
#define GOOMBA_BBOX_HEIGHT_DIE 9


#define GOOMBA_STATE_WALKING		100
#define GOOMBA_STATE_DIE			200
#define GOOMBA_STATE_BEING_STROMPED	300
#define GOOMBA_STATE_BEING_SKILLED	400
#define GOOMBA_STATE_INACTIVE		500
#define GOOMBA_STATE_DEATH			600

#define GOOMBA_ANI_WALKING			0
#define GOOMBA_ANI_DIE				1

#define GOOMA_INACTIVE_TIME		500

//=====================PARA GOOMBA===========
#define PARAGOOMBA_BBOX_WIDTH			20
#define PARAGOOMBA_BBOX_HEIGHT_FLAPPING	24
#define PARAGOOMBA_BBOX_HEIGHT_WALKING	18
#define PARAGOOMBA_GRAVITY				0.002f
#define PARAGOOMBA_WALKING_SPEED		0.03f
#define PARAGOOMBA_JUMP_SPEED			0.02f
#define PARAGOOMBA_SUPER_JUMP_SPEED		0.3f

#define PARAGOOMBA_STATE_WALKING			0
#define PARAGOOMBA_STATE_FLAPPING			1
#define PARAGOOMBA_STATE_SUPER_JUMPING		2
#define PARAGOOMBA_STATE_DEATH				4
#define PARAGOOMBA_STATE_INACTIVE			5
#define PARAGOOMBA_STATE_GOOMBA				6

#define PARAGOOMBA_ANI_WALKING			0
#define PARAGOOMBA_ANI_JUMPING			1

#define PARAGOOMBA_SWITCH_STATE_TIME	1000
#define GOOMA_DEATH_TIME				500

//KoopaTroopa
#define KOOPATROOPA_RED_TYPE	0
#define KOOPATROOPA_GREEN_TYPE	1

#define KOOPATROOPA_WALKING_SPEED				0.03f
#define KOOPATROOPA_GRAVITY						0.002f
#define KOOPATROOPA_BUMP_SPEED					0.12f
#define KOOPATROOPA_DIE_DEFLECT_SPEED_Y			0.3f
#define KOOPATROOPA_DIE_DEFLECT_SPEED_X			0.1f
#define KOOPATROPPA_EXIT_HIDING_DEFLECT_SPEED	0.01f
#define KOOPATROOPA_DEFLECT_HOLDING_X			3
#define KOOPATROOPA_DEFLECT_HOLDING_Y			3.5f/10
#define KOOPATROOPA_EXIT_SHELL_TIME				5000
#define KOOPATROOPA_DEATH_TIME				1200
#define KOOPATROOPA_TURN_WALKING_TIME			500

#define KOOPATROOPA_BBOX_WIDTH					16
#define KOOPATROOPA_BBOX_HEIGHT					26
#define KOOPATROOPA_BBOX_HEIGHT_HIDING			16


#define KOOPATROOPA_STATE_WALKING				100
#define KOOPATROOPA_STATE_HIDING				200
#define KOOPATROOPA_STATE_IS_PICKED_UP			300
#define KOOPATROOPA_STATE_BEING_SKILLED			400
#define KOOPATROOPA_STATE_IS_BUMPED				500
#define KOOPATROOPA_STATE_INACTIVE				600
#define KOOPATROOPA_STATE_EXIT_SHELL			700
#define KOOPATROOPA_STATE_DEATH					800


#define KOOPATROOPA_GREEN_ANI_WALKING			0
#define KOOPATROOPA_GREEN_ANI_HIDING			1
#define KOOPATROOPA_GREEN_ANI_BUMPING			2
#define KOOPATROOPA_RED_ANI_WALKING				3
#define KOOPATROOPA_RED_ANI_HIDING				4
#define KOOPATROOPA_RED_ANI_BUMPING				5
#define KOOPATROOPA_GREEN_ANI_EXIT_SHELL		6
#define KOOPATROOPA_RED_ANI_EXIT_SHELL			7
//PARATROOPA
#define PARATROOPA_BBOX_WIDTH			16
#define PARATROOPA_BBOX_HEIGHT			27
#define PARATROOPA_GRAVITY				0.002f
#define PARATROOPA_WALKING_SPEED		0.05f
#define PARATROOPA_JUMP_SPEED			0.3f

#define PARATROOPA_STATE_JUMPING			0
#define PARATROOPA_STATE_DEATH				1
#define PARATROOPA_STATE_INACTIVE			2
#define PARATROOPA_STATE_KOOPA				3

#define PARATROOPA_ANI_FLAPPING				0
#define PARATROOPA_ANI_DEATH				1

#define PARATROOPA_SWITCH_STATE_TIME		1000
#define PARATROOPA_DEATH_TIME				500




//PiranhaPlant
#define PIRANHAPLANT_GREEN_TYPE					0
#define PIRANHAPLANT_RED_TYPE					1

#define PIRANHAPLANT_BBOX_WIDTH					16
#define PIRANHAPLANT_BBOX_HEIGHT				32
#define PIRANHAPLANT_DARTING_SPEED				0.03f
#define PIRANHAPLANT_BBOX_DEATH_WIDTH			16
#define PIRANHAPLANT_BBOX_DEATH_HEIGHT			16

#define PIRANHAPLANT_STATE_DARTING				0
#define PIRANHAPLANT_STATE_BITING				100
#define PIRANHAPLANT_STATE_DEATH				200
#define PIRANHAPLANT_STATE_INACTIVE				300

#define PIRANHAPLANT_GREEN_ANI_DARTING		0
#define PIRANHAPLANT_GREEN_ANI_BITING		1
#define PIRANHAPLANT_RED_ANI_DARTING		2
#define PIRANHAPLANT_RED_ANI_BITING			3
#define PIRANHAPLANT_ANI_DEATH				4

#define PIRANHAPLANT_SWITCHING_STATE_TIME	1000
#define PIRANHAPLANT_INACTIVE_TIME			800
//Fire PiranhaPlant
//PiranhaPlant
#define FIREPIRANHAPLANT_GREEN_TYPE	0
#define FIREPIRANHAPLANT_RED_TYPE	1

#define FIREPIRANHAPLANT_BBOX_WIDTH				16
#define FIREPIRANHAPLANT_BBOX_HEIGHT			32
#define FIREPIRANHAPLANT_DARTING_SPEED			0.04f
#define FIREPIRANHAPLANT_BBOX_DEATH_WIDTH		16
#define FIREPIRANHAPLANT_BBOX_DEATH_HEIGHT		16
#define FIREPIRANHAPLANT_FREEFIRE_MAX_ZONE_X	132
#define FIREPIRANHAPLANT_FREEFIRE_MIN_ZONE_X	32
#define FIREPIRANHAPLANT_TARGET_X				103
#define FIREPIRAHANPLANT_SHOOTING_X				5


#define FIREPIRANHAPLANT_STATE_DARTING		0
#define FIREPIRANHAPLANT_STATE_SHOOTING		100
#define FIREPIRANHAPLANT_STATE_DEATH		200
#define FIREPIRANHAPLANT_STATE_INACTIVE		300

#define FIREPIRANHAPLANT_GREEN_ANI_DARTING_BOTTOM	0
#define FIREPIRANHAPLANT_GREEN_ANI_DARTING_TOP		1
#define FIREPIRANHAPLANT_GREEN_ANI_SHOOTING_BOTTOM	2
#define FIREPIRANHAPLANT_GREEN_ANI_SHOOTING_TOP		3

#define FIREPIRANHAPLANT_RED_ANI_DARTING_BOTTOM		4
#define FIREPIRANHAPLANT_RED_ANI_DARTING_TOP		5
#define FIREPIRANHAPLANT_RED_ANI_SHOOTING_BOTTOM	6
#define FIREPIRANHAPLANT_RED_ANI_SHOOTING_TOP		7
#define FIREPIRANHAPLANT_ANI_DEATH					8


#define FIREPIRANHAPLANT_INACTIVE_TIME		800
#define FIREPIRANHAPLANT_SHOOTING_TIME		1500
#define FIREPIRANHAPLANT_SWITCH_TIME		3000
//FIREBALL
#define FIREBALL_GRAVITY		0.008f
#define FIREBALL_SPEED_NX		0.15f
#define FIREBALL_SPEED_NY		0.09f
#define FIREBALL_BBOX_HEIGHT	16
#define FIREBALL_BBOX_WIDTH		8
#define FIREBALL_STATE_NORMAL	100
#define FIREBALL_STATE_EXPLODE	200
#define FIREBALL_STATE_INACTIVE	300
#define FIREBALL_ANI_NORMAL		0
#define FIREBALL_ANI_EXPLODE	1
#define FIREBALL_INACTIVE_TIME	200
//Fireball of PiranhaPlant
#define FIREBULLET_SPEED_NX		0.05f
#define FIREBULLET_SPEED_NY_1	0.02f
#define FIREBULLET_SPEED_NY_2	0.06f
#define FIREBULLET_BBOX_HEIGHT	8
#define FIREBULLET_BBOX_WIDTH	8

#define FIREBULLET_DIRECT_1		1
#define FIREBULLET_DIRECT_2		2
#define FIREBULLET_DIRECT_3		3
#define FIREBULLET_DIRECT_4		4
//GROUND
#define GROUND_BBOX_WIDTH		16
#define GROUND_BBOX_HEIGHT		16
//Block
#define BLOCK_BBOX_WIDTH		16
#define BLOCK_BBOX_HEIGHT		16
#define ID_TEX_BBOX				-100
// special texture to draw object bounding box
//Brick
#define BRICK_BBOX_WIDTH		16
#define BRICK_BBOX_HEIGHT		16

#define	BRICK_STATE_NORMAL		0
#define BRICK_STATE_EMPTY		1
#define BRICK_STATE_BREAK		2
#define BRICK_STATE_INACTIVE	4

#define BRICK_ANI_NORMAL		0
#define BRICK_ANI_EMPTY			1

#define BRICK_DEFLECT_SPEED		0.02f
#define BRICK_GRAVITY			0.002f
#define BRICK_CHANGE_TIME		3000

#define BRICK_ITEM_COIN_TYPE		1
#define BRICK_ITEM_EXTRA_LIFE_TYPE	2
#define BRICK_STARTMAN_TYPE			3
#define BRICK_POWER_UP_TYPE			4
#define BRICK_BREAKABLE_TYPE		5
#define BRICK_PSWITCH_TYPE			6



//Raccoon Leaf 
#define RACCOONLEAF_BBOX_WIDTH		16
#define RACCOONLEAF_BBOX_HEIGHT		14
#define RACCOONLEAF_SPEED_APPEARANCE_Y	0.3f
#define RACCOONLEAF_GRAVITY				0.002f
#define RACCOONLEAF_SPEED_X				0.03f
#define RACCOONLEAF_SPEED_FALL			0.04f
#define RACCOONLEAF_CHANGE_DIRECT_TIME	500

#define RACCOONLEAF_STATE_APPEARANCE	100
#define RACCOONLEAF_STATE_INACTIVE		200

#define RACCOONLEAF_ANI_NORMAL			0
//MUSHROOM

#define MUSHROOM_TYPE_1UP			1
#define MUSHROOM_TYPE_POWERUP		0


#define MUSHROOM_BBOX_WIDTH			16
#define MUSHROOM_BBOX_HEIGHT		16
#define MUSHROOM_SPEED_APPEARANCE_Y	0.02f
#define MUSHROOM_GRAVITY			0.002f
#define MUSHROOM_SPEED_X			0.045f
#define MUSHROOM_APPEARED_TIME		2000

#define MUSHROOM_STATE_APPEARANCE	100
#define MUSHROOM_STATE_INACTIVE		200
#define MUSHROOM_STATE_WALKING		300

#define MUSHROOM_ANI_POWERUP		0
#define MUSHROOM_ANI_1UP			1
// PSWITCH
#define PSWITCH_BBOX_WIDTH			16
#define PSWITCH_BBOX_HEIGHT			16
#define PSWITCH_PRESSED_BBOX_HEIGHT	7
#define PSWITCH_PRESS_APPEAR_TIME	200
#define PSWITCH_SPEED_APPEAR		0.1f
#define PSWITCH_TRANSFORM_TIME		3000

#define PSWITCH_STATE_APPEAR		0
#define PSWITCH_STATE_PRESSED		1
#define PSWITCH_STATE_INACTIVE		2

#define PSWITCH_ANI_APPEAR			0
#define PSWITCH_ANI_PRESSED			1


//Invisible Brick
#define INVISIBLEBRICK_TYPE_GROUND	0
#define INVISIBLEBRICK_TYPE_BLOCK	1

//COIN
#define COIN_TYPE_1		1
#define COIN_TYPE_2		2
#define COIN_TYPE_3		3

#define COIN_ANI_TYPE_1	0
#define COIN_ANI_TYPE_2	1

#define COIN_STATE_IDLE		0
#define COIN_STATE_INACTIVE	100
#define COIN_STATE_APPEAR	200

#define COIN_BBOX_WIDTH		14
#define COIN_BBOX_HEIGHT	16
#define COIN_SPEED_DELECT_Y	0.3f
#define COIN_GRAIVITY		0.001f

//Game PLAY 
#define SCENE_SECTION_UNKNOWN			-1
#define SCENE_SECTION_TEXTURES			2
#define SCENE_SECTION_SPRITES			3
#define SCENE_SECTION_ANIMATIONS		4
#define SCENE_SECTION_ANIMATION_SETS	5
#define SCENE_SECTION_OBJECTS			6
#define SCENE_SECTION_MAPS				7
#define SCENE_SECTION_GRID				8



#define OBJECT_TYPE_MARIO				0
#define OBJECT_TYPE_BRICK				1
#define OBJECT_TYPE_GOOMBA				2
#define OBJECT_TYPE_KOOPAS				3
#define OBJECT_TYPE_BLOCKS				5
#define OBJECT_TYPE_GROUNDS				4
#define OBJECT_TYPE_PIPES				6
#define OBJECT_TYPE_INVISIBLEBRICK		7
#define OBJECT_TYPE_PIRANHAPLANT		8
#define OBJECT_TYPE_COIN				9
#define OBJECT_TYPE_FIREPIRANHAPLANT	10
#define OBJECT_TYPE_PARAGOOMBA			11
#define OBJECT_TYPE_PARATROOPA			12
#define OBJECT_TYPE_PORTAL				50
#define MAX_SCENE_LINE					1024
//GAME
#define MAX_GAME_LINE 1024
#define GAME_FILE_SECTION_UNKNOWN -1
#define GAME_FILE_SECTION_SETTINGS 1
#define GAME_FILE_SECTION_SCENES 2
//Tile Map
#define TILE_WIDTH 16
#define TILE_HEIGHT 16

//Pipe
#define PIPE_BBOX_WIDTH  30
#define PIPE_BBOX_HEIGHT 16
//SETTING
#define WINDOW_CLASS_NAME L"SuperMarioBros3"
#define MAIN_WINDOW_TITLE L"Super Mario Bros 3"
#define BACKGROUND_COLOR D3DCOLOR_XRGB(181, 236, 243)
#define SCREEN_WIDTH  354
#define SCREEN_HEIGHT 240
#define MAX_FRAME_RATE 120
